//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPeluqueria.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Prod
    {
        public string num_Res { get; set; }
        public string id_Prod { get; set; }
        public string cantidad_Reservada { get; set; }
        public System.DateTime fecha_Reserva { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Reservas Reservas { get; set; }
    }
}
