//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPeluqueria.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPeluqueriaEntities2 : DbContext
    {
        public BDPeluqueriaEntities2()
            : base("name=BDPeluqueriaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casa_Comerc> Casa_Comerc { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Peluqueros> Peluqueros { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Res_Prod> Res_Prod { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
